insert into PAAS_APPDEV_PRODUCTS (NAME, WEBURL) values ('JCS','https://cloud.oracle.com/en_US/java')
insert into PAAS_APPDEV_PRODUCTS (NAME, WEBURL) values ('ACC','https://cloud.oracle.com/en_US/acc')
insert into PAAS_APPDEV_PRODUCTS (NAME, WEBURL) values ('Mobile','https://cloud.oracle.com/en_US/mobile')
insert into PAAS_APPDEV_PRODUCTS (NAME, WEBURL) values ('Messaging','https://cloud.oracle.com/en_US/messaging')
insert into PAAS_APPDEV_PRODUCTS (NAME, WEBURL) values ('Developer','https://cloud.oracle.com/en_US/developer_service')
insert into PAAS_APPDEV_PRODUCTS (NAME, WEBURL) values ('App_Builder','https://cloud.oracle.com/en_US/application-builder')